
var tableConten = []
var alunos = ["ANTONIO KACIO PEREIRA DOS SANTOS",
"ARTHUR MORAIS LOPES DOS REIS","AUGUSTO LOYOLA ALVES SANTANA","BRUNO BEZERRA DA SILVA",
"CARLOS GABRIEL LUCIO","DAPHNE CARLOS CORREIA DA SILVA","DIEGO FONSECA PEREIRA",
"ENZO MATEUS GONCALVES","EVELYN BEATRIZ DA SILVA","FELIPE CORREIA RIBEIRO",
"FRANCYNE LEONARDO RODRIGUES","GEOVANNA ABADE DOS SANTOS","GUILHERME DE PAULA PINTO WANDERLEY",
"GUSTAVO NUNES ALVES","IGOR SILVA COSTA","JESSICA DA SILVA EZEQUIEL",
"JOAO PEDRO DA SILVA COUTINHO","LEONARDO OLIVEIRA COSTA LOMES",
"LUCCAS PEREIRA FORMICKI","MARCELO SANTOS ANNUNCIACAO",
"MARIANA MARTINS DE MENEZES","MATHEUS BORGES DOS SANTOS",
"MATHEUS VITALINO DOS SANTOS","NICOLE DOS SANTOS PEREIRA","RAMON VIANA SOUZA",
"RODRIGO SBEGHEN IUMATTI COLETTO","ULISSES DUO GITTI FLOR","VINICIUS DE LIMA OLIVEIRA",
"VINICIUS HAGOP CASSAPIAN BARBOSA","YURI JONATHAN DOMINGOS"
]

for(let i = 0; i<alunos.length; i++){
    tableConten.push(alunos)
}
//console.log(tableConten.name)
const tbodies = document.getElementById('tabledata');
let dataHTML = '';
    
for(let i = 0; i < tableConten.length; i++){        
    dataHTML += `<tr><td>${i}</td><td>${alunos[i]}</td></tr>`;
}
    //Table isnt in the DOM yet. It will be put now
tbodies.innerHTML = dataHTML;

